### ISSUE TITLE
実装: `IdeaListItem`

### ISSUE THREAD

**Issue by mgn901** [geekcamp2023-vol2-team31/frontend-2#1]

**Comment by bildeneins** [comment]
<img width="193" alt="スクリーンショット 2023-05-27 20 26 17" src="https://github.com/geekcamp2023-vol2-team31/frontend-2/assets/49736209/03e3a019-9c56-40fb-a640-bd8678cd2697">

**Comment by bildeneins** [comment]
仕様: https://scrapbox.io/geekcomp/%E3%82%A2%E3%82%A4%E3%83%87%E3%82%A3%E3%82%A2%E5%87%BA%E3%81%97%E7%94%BB%E9%9D%A2
